[book]
authors = ["Lichtblick Team"]
language = "en"
multilingual = false
src = "src"
title = "Lichtblick Documentation"

[preprocessor.tabs]

[output.html]
static-files = ["images"]
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]