name: Deploy Documentation to GH Pages

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build docusaurus static files
        run: yarn build
